#!/usr/bin/env bash
# Script installs Nginx on a server
 
sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' | sudo tee /var/www/html/index.html
echo "
server {
        listen 80 default_server;
        listen [::]:80 default_server;
 
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
 
        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
 
}" | sudo tee /etc/nginx/sites-available/default
sudo service nginx start
