#!/usr/bin/env bash
# a script that installs and redirects /redirect_me on nginx server
#!/usr/bin/env bash
# a script that installs and redirects /redirect_me on nginx server
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }

}" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart


# example sed tutuorial
# new_config="start\n\tserver_name \_\;\n\tlocation \/redirect_me \{\n\treturn 301 \$scheme\:\/\/\$host_name\;\n\}\n"
# new_config="\/redirect_me https\:\/\/www.youtube.com\/watch\?v\=QH2\-TGUlwu4 permanent\;"
# sed -i "s/start/$new_config/" test
