#!/usr/bin/env bash
# Installs and configures HAproxy on webserver 3, distributes requests
# using a roundrobin algorithm
 

 
sudo apt-get update
sudo apt-get upgrade
 
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy
sudo apt-get -y update
 
sudo apt-get -y install haproxy
 
balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
 
backend webservers
    balance roundrobin
    server 54330-web-01 3.84.238.96:80 check
    server 54330-web-02 3.83.227.71:80 check
"
echo "$balancer" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
