#!/usr/bin/env bash
#script that displays the time for 12 hours and 59 minutes
#display hours from 0 to 12 using while loop
#display minutes from 1 to 59

Hour=0
while [ $Hour -lt 13 ]
do
	echo "Hour: $Hour"
	minute=1
	while [ $minute -lt 60 ]
	do 
		echo "$minute"
		((minute++))
	done
	((Hour++))
done

